### ISSUE TITLE
MegaPixImage fails for strict-di

### ISSUE THREAD

**Issue by vjoao** [CrackerakiUA/ui-cropper#14]
I'm using ES6 with webpack and strict di.

The error I'm getting after importing 'uiCropper' is: 
```
Error: [$injector:strictdi] MegaPixImage is not using explicit annotation and cannot be invoked in strict mode
```

even though MegaPixImage has nothing to do with angular.
Any thoughts?

**Comment by CrackerakiUA** [comment]
Never seen this before.

**Comment by vjoao** [comment]
Found the issue.
Your module definition is actually exporting the MegaPixImage function for some reason.

I was doing:

`import uiCropper from 'ui-cropper';`

```
angular.module('app', [
...
uiCropper
]
```

but uiCropper in this context is not `uiCropper`, it is actually `MegaPixImage`.
I guess you have to review your module definitions.

**Comment by xitasoappdev** [comment]
same error for me. unfortunately not working with Angular 1.6

**Comment by CrackerakiUA** [comment]
Probably we use this module differently, can you provide an solution for this problem?

**Comment by rickerd** [comment]
No suggestions are made, closing for now.

**Comment by RubcovSA** [comment]
Does anybody solve it?

**Comment by gamegenius86** [comment]
This is caused by final function (iife) in the compiled unminified version of the code to include `module.exports = MegaPixImage`.  To solve this the compiled version must do the module export `module.exports = 'uiCropper';` last.

Solution for the time being would be to just require above your `angular.module()` definition and manually put `uiCropper` as a dependancy.

**Comment by CrackerakiUA** [comment]
feel free to make PR
